Repository CUBRID/cubrid-manager, pull requests merged in 2019-04, with the labels that each got.

#151 [TOOLS-4320] [CM] When a user try to change the database under multiple query editors were opened, CM always changes the database associated with the query editor latest created.
  com.cubrid.common.ui/src/com/cubrid/common/ui/query/control/EditorToolBar.java
Labels: enhancement

#152 [TOOLS-4321] [CM] When a user expands "More Tables" node, all table folders' table count is updated.
  com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/MoreTablesNode.java
Labels: bug

#150 [TOOLS-4319] [CM] Change properties of unfolding 'Table' icon in 'Host Navigation' windows
  com.cubrid.common.ui/plugin.properties
  com.cubrid.common.ui/plugin.xml
  com.cubrid.common.ui/plugin_jp_JP.properties
  com.cubrid.common.ui/plugin_km_KH.properties
  com.cubrid.common.ui/plugin_ko_KR.properties
  com.cubrid.common.ui/plugin_tr_TR.properties
  com.cubrid.common.ui/plugin_zh_CN.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.java
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_jp_JP.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_km_KH.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_ko_KR.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_tr_TR.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/Messages_zh_CN.properties
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/GeneralPreference.java
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/NavigatorPreference.java
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/NavigatorPreferenceComposite.java
  com.cubrid.common.ui/src/com/cubrid/common/ui/common/preference/NavigatorPreferencePage.java
  com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/MoreTablesNode.java
  com.cubrid.common.ui/src/com/cubrid/common/ui/spi/model/loader/schema/CubridTablesFolderLoader.java
  com.cubrid.cubridmanager.app/src/com/cubrid/cubridmanager/app/CMPreferenceNodeComparator.java
Labels: enhancement

#153 update version
  com.cubrid.cubridmanager.ui/version.properties
Labels: release

#154 update version
  com.cubrid.cubridmanager.ui/version.properties
Labels: release
